SELECT NAME 
FROM
(SELECT NAME, DAY(CREATED_AT), COUNT(*) AS COUNT 
FROM POST
INNER JOIN USER
ON USER.ID = POST.USER_ID
WHERE POST.CREATED_AT BETWEEN CURDATE () AND CURDATE () + 1 
GROUP BY USER_ID HAVING COUNT(POST.ID) > 3) AS G;